defaults: &defaults
  docker:
    - image: docker

version: 2
jobs:
  site:build:
    <<: *defaults
    steps:
      - checkout
      - run: apk update && apk add make curl git
      - run: git submodule update --init --recursive

      - run: make setup
      - run: make build

  site:publish:
    <<: *defaults
    steps:
      - checkout
      - run: apk update && apk add make curl git openssh
      - run: git submodule update --init --recursive

      - add_ssh_keys:
          fingerprints:
            - "85:b5:d3:31:95:4d:bf:ac:8f:86:9c:23:21:f9:fb:73"
      - run:
          name: Setup git
          command: |
            git config --global user.email "circleci@polarsquad.com"
            git config --global user.name "CircleCI"
            echo 'github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      - run: make setup
      - run: make publish

workflows:
  version: 2
  site:
    jobs:
      - site:build:
          filters:
            branches:
              ignore: /gh-pages/

      - site:publish:
          requires:
            - site:build
          filters:
            branches:
              ignore: /gh-pages/
              only: /master/
