baseURL = "https://polarsquad.github.io/kubernetes-developer-workshop/"
languageCode = "en-us"
title = "Kubernetes Developer Workshop"
copyright = "Made with ❤️ for Developers by Polar Squad. Content on this site is licensed under a Creative Commons license"
googleAnalytics = "UA-xxxx-1"
theme = "hugo-apex-theme"
pygmentsCodeFences = true
pygmentsStyle = "dracula"
enableEmoji = true
canonifyurls = true

[params]
logo = "/290x132_PolarSquad_logo.png"
